Repository EleutherAI/elk, pull requests merged in 2023-03, with the labels that each got.

#95 Migrate to HF datasets for storing extracted hidden states
  elk/__main__.py
  elk/extraction/__init__.py
  elk/extraction/extraction.py
  elk/extraction/extraction_main.py
  elk/extraction/generator.py
  elk/extraction/prompt_dataset.py
  elk/files.py
  elk/list.py
  elk/resources/adjectives.json
  elk/resources/names.json
  elk/training/preprocessing.py
  elk/training/reporter.py
  elk/training/train.py
  elk/utils/__init__.py
  elk/utils/data_utils.py
  elk/utils/distributed.py
  elk/utils/gpu_utils.py
  elk/utils/typing.py
Labels: refactor

#114 Switch back to imap_unordered in training while ensuring CSV is still sorted
  elk/training/train.py
Labels: enhancement

#117 PCA init MVP
  elk/training/reporter.py
Labels: enhancement

#127 Fix: PromptDataset inserting fake labels into its output
  elk/extraction/prompt_dataset.py
Labels: bug

#160 split max_examples between processes
  elk/extraction/balanced_sampler.py
  elk/extraction/extraction.py
  elk/logging.py
Labels: bug
